name: cs7643-final-project
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.6.0=h6a678d5_0
  - black=24.10.0=py312h06a4308_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py312h6a678d5_9
  - brotlicffi=1.0.9.2=py312h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.2.25=h06a4308_0
  - cairo=1.16.0=he5ede1b_6
  - certifi=2025.6.15=py312h06a4308_0
  - cffi=1.17.1=py312h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.8=py312h06a4308_0
  - contourpy=1.3.1=py312hdb19cb5_0
  - cuda-cudart=12.4.127=h99ab3db_0
  - cuda-cudart_linux-64=12.4.127=hd681fbe_0
  - cuda-cupti=12.4.127=h6a678d5_1
  - cuda-libraries=12.4.1=h06a4308_1
  - cuda-nvrtc=12.4.127=h99ab3db_1
  - cuda-nvtx=12.4.127=h6a678d5_1
  - cuda-opencl=12.4.127=h6a678d5_0
  - cuda-runtime=12.4.1=hb982923_0
  - cuda-version=12.4=hbda6634_3
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dav1d=1.2.1=h5eee18b_0
  - deprecated=1.2.13=py312h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=6.1.1=h2a67f75_3
  - filelock=3.17.0=py312h06a4308_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.55.3=py312h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - fsspec=2025.5.1=py312he3bba80_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py312h5eee18b_0
  - graphite2=1.3.14=h295c915_1
  - h5py=3.14.0=py312he0d80d8_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - hdf5=1.14.5=h2b7332f_2
  - icu=73.1=h6a678d5_0
  - idna=3.7=py312h06a4308_0
  - importlib-metadata=8.5.0=py312h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.6=py312h06a4308_0
  - jpeg=9e=h5eee18b_3
  - kagglehub=0.2.7=py312h06a4308_0
  - kiwisolver=1.4.8=py312h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libarchive=3.7.7=hfab0078_0
  - libcublas=12.4.5.8=h99ab3db_1
  - libcufft=11.2.1.3=h99ab3db_1
  - libcufile=1.9.1.3=h99ab3db_1
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.5.147=h99ab3db_1
  - libcurl=8.12.1=hc9e6f67_0
  - libcusolver=11.6.1.9=h99ab3db_1
  - libcusparse=12.3.1.170=h99ab3db_1
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.2.5.30=h99ab3db_1
  - libnvfatbin=12.4.127=h7934f7d_2
  - libnvjitlink=12.4.127=h99ab3db_1
  - libnvjpeg=12.3.1.117=h6a678d5_1
  - libogg=1.3.5=h27cfd23_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=hdbd6064_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtheora=1.1.1=h7f8727e_3
  - libtiff=4.7.0=hde9077f_0
  - libtorch=2.5.1=cpu_mkl_h77e34b5_104
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py312h5eee18b_0
  - matplotlib=3.10.0=py312h06a4308_0
  - matplotlib-base=3.10.0=py312hbfdbfaf_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_2
  - mkl_fft=1.3.11=py312h5eee18b_0
  - mkl_random=1.2.8=py312h526ad5a_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpi=1.0=mpich
  - mpi4py=4.0.3=py312hb6b6513_0
  - mpich=4.1.1=hbae89fd_0
  - mpmath=1.3.0=py312h06a4308_0
  - mypy_extensions=1.0.0=py312h06a4308_0
  - mysql=8.4.0=h721767e_2
  - ncurses=6.4=h6a678d5_0
  - networkx=3.4.2=py312h06a4308_0
  - numpy=1.26.4=py312hc5e2394_0
  - numpy-base=1.26.4=py312h0da6c21_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.0.16=h5eee18b_0
  - opentelemetry-api=1.30.0=py312h06a4308_0
  - packaging=24.2=py312h06a4308_0
  - pathspec=0.10.3=py312h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pillow=11.1.0=py312hac6e08b_1
  - pip=25.1=pyhc872135_2
  - pixman=0.40.0=h7f8727e_1
  - platformdirs=4.3.7=py312h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pyparsing=3.2.0=py312h06a4308_0
  - pyqt=6.7.1=py312h6a678d5_1
  - pyqt6-sip=13.9.1=py312h5eee18b_1
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.11=h22baa00_0
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - pytorch=2.5.1=cpu_mkl_py312h8be6507_104
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py312h5eee18b_0
  - qtbase=6.7.3=hdaa5aa8_0
  - qtdeclarative=6.7.3=h6a678d5_0
  - qtsvg=6.7.3=he621ea3_0
  - qttools=6.7.3=h80c7b02_0
  - qtwebchannel=6.7.3=h6a678d5_0
  - qtwebsockets=6.7.3=h6a678d5_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.4=py312h06a4308_0
  - setuptools=78.1.1=py312h06a4308_0
  - sip=6.10.0=py312h6a678d5_0
  - six=1.17.0=py312h06a4308_0
  - sleef=3.5.1=h5eee18b_2
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.3=py312h06a4308_1
  - tbb=2021.8.0=hdb19cb5_0
  - tesseract=5.2.0=h6a678d5_2
  - tk=8.6.14=h993c535_1
  - torchtriton=3.1.0=py312
  - torchvision=0.20.1=cpu_py312h1c79344_2
  - tornado=6.5.1=py312h5eee18b_0
  - tqdm=4.67.1=py312he106c6f_0
  - typing_extensions=4.12.2=py312h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=15.1.0=py312h5eee18b_1
  - urllib3=2.5.0=py312h06a4308_0
  - wheel=0.45.1=py312h06a4308_0
  - wrapt=1.17.0=py312h5eee18b_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.21.0=py312h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
prefix: /home/jon/anaconda3/envs/cs7643-final-project
